2023-12-30 23:24:18,482 ERROR: Exception on /index [GET] [in /home/driiisdev/Desktop/dev/microblog/venv/lib/python3.8/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/driiisdev/Desktop/dev/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/driiisdev/Desktop/dev/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/driiisdev/Desktop/dev/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/driiisdev/Desktop/dev/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/driiisdev/Desktop/dev/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/driiisdev/Desktop/dev/microblog/app/routes/page.py", line 19, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts)
  File "/home/driiisdev/Desktop/dev/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/driiisdev/Desktop/dev/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/driiisdev/Desktop/dev/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/driiisdev/Desktop/dev/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/driiisdev/Desktop/dev/microblog/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/driiisdev/Desktop/dev/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/driiisdev/Desktop/dev/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/driiisdev/Desktop/dev/microblog/app/templates/index.html", line 20, in template
    {% {% include "_post.html" %} %}
jinja2.exceptions.TemplateSyntaxError: tag name expected
2023-12-31 14:10:55,093 INFO: Microblog startup [in /home/driiisdev/Desktop/dev/microblog/app/__init__.py:36]
