2024-03-29 15:30:36,485 ERROR: Exception on /login [GET] [in /home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/driiisdev/dev/microblog/app/routes/login.py", line 23, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/driiisdev/dev/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/driiisdev/dev/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/home/driiisdev/dev/microblog/app/templates/login.html", line 24, in block 'content'
    Forgot Your Password? <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1074, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1063, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 919, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2024-03-29 15:30:38,497 ERROR: Exception on /login [GET] [in /home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/driiisdev/dev/microblog/app/routes/login.py", line 23, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/driiisdev/dev/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/driiisdev/dev/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/home/driiisdev/dev/microblog/app/templates/login.html", line 24, in block 'content'
    Forgot Your Password? <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1074, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1063, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 919, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2024-03-29 15:31:15,289 INFO: Microblog startup [in /home/driiisdev/dev/microblog/app/__init__.py:38]
2024-03-29 15:32:47,821 INFO: Microblog startup [in /home/driiisdev/dev/microblog/app/__init__.py:38]
2024-03-29 17:00:35,564 INFO: Microblog startup [in /home/driiisdev/dev/microblog/app/__init__.py:38]
2024-03-29 17:40:19,216 INFO: Microblog startup [in /home/driiisdev/dev/microblog/app/__init__.py:38]
2024-03-29 17:43:09,951 INFO: Microblog startup [in /home/driiisdev/dev/microblog/app/__init__.py:38]
2024-03-30 17:09:45,656 INFO: Microblog startup [in /home/driiisdev/dev/microblog/app/__init__.py:38]
2024-03-30 17:39:14,459 INFO: Microblog startup [in /home/driiisdev/dev/microblog/app/__init__.py:40]
